version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
    container_name: frontend
    restart: unless-stopped
    ports:
      - '3000:3000'
    volumes:
      - ./frontend:/app
      - /app/node_modules/
